# -*- coding: utf-8 -*-
"""KickBoard helmet Detection yolov4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTYDzSQClGDi5zBaX9LN_mxj_4LKSGbN
"""

from google.colab import drive
drive.mount('/content/drive')

!mkdir /content/darknet

!unzip "/content/drive/MyDrive/Colab Notebooks/kb_Detection_Darknet.zip" -d "/content/darknet"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet

!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile
!sed -i 's/LIBSO=0/LIBSO=1' Makefile

!make
!chmod +x ./darknet

!rm -rf /content/darknet/backup
!ln -s /content/drive/'MyDrive'/YOLOv4-tiny/backup /content/darknet

!sudo apt install dos2unix

!dos2unix ./data/list/train.txt
!dos2unix ./data/list/valid.txt
!dos2unix ./data/list/test.txt
!dos2unix ./data/ClassNames.names
!dos2unix ./data/kbDatas.data
!dos2unix ./cfg/yolov4-tiny-custom.cfg

# Commented out IPython magic to ensure Python compatibility.
def imShow(path): 
  import cv2 
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image, (3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

def upload():
  from google.colab import files
  uploaded = files.upload()
  for name, data in uploaded.items():
    with open(name, 'wb') as f:
      f.write(data)
      print('saved file', name)
def download(path):
  from google.colab import files
  files.download(path)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.conv.29

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet

!time ./darknet detector train data/kbDatas.data cfg/yolov4-tiny-custom.cfg yolov4-tiny.conv.29 -dont_show -map l tee train.log

!cp -r /content/darknet/train.log /content/drive/'MyDrive'/YOLOv4-tiny/backup/

from google.colab.patches import cv2_imshow

imShow('chart.png')

!time ./darknet detector test data/kbDatas.data cfg/yolov4-tiny-custom.cfg backup/yolov4-tiny-custom_final.weights -dont_show -ext_output <data/list/test.txt> result_v4.txt 
download('result_v4.txt')

!time ./darknet detector test data/kbDatas.data cfg/yolov4-tiny-custom.cfg backup/yolov4-tiny-custom_final.weights data/images/0026_jpg.rf.c601665d01f806d12713012ab951e697.jpg
imShow('predictions.jpg')
download('predictions.jpg')